language: cpp
os: 
  - osx
  - linux
compiler: gcc
sudo: true
#before_install:
#  - test -n $CC && unset CC
#  - test -n $CXX && unset CXX
#  - export CC=mpicc
#  - export CXX=mpicxx
install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo rm /usr/local/include/c++ ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install mpich2 lapack ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install cmake mpich2 liblapack-dev ; fi
before_script: 
  - mkdir build
  - cd build
  - cmake ..
script: make && make test
